version: '3.9'

services:
  baseline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baseline_notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work
