version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=dev
  # opcional: cliente para pruebas
  client:
    image: python:3.11-slim
    command: ["python", "/app/scr/client/client.py"]
    volumes:
      - .:/app
    depends_on:
      - api