global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'alert-server'
    static_configs:
      - targets: ['alert-server:9000']

  - job_name: 'monitor'
    static_configs:
      - targets: ['monitor:8002']
